FROM python:3.11
WORKDIR /app
COPY ./web_app/main.py /app
COPY web_app/requirements.txt /app
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
